name: ci

on: [push, pull_request]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: orderdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: copy .env file
        run: cp .env.example .env || echo ".env already exists"

      - name: Compose containers up
        run: docker-compose up --build

      - name: Verify Containers
        run: docker ps

      - name: Compose containers down
        run: docker-compose down -v
